name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 自动运行
  workflow_dispatch:     # 可手动触发

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      
      - name: Configure git
        run: |
          git config user.name "lh728"
          git config user.email "65521533+lh728@users.noreply.github.com"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Run script
        run: python update.py
      
      - name: Push
        run: |
          git push origin HEAD:main

